#!/bin/bash
# Theme changed: swap the fastfetch / About logo.
#
# ~/.config/omarchy/branding/about.txt is global branding, not part of a theme,
# so scoping the Osiris eye to the Osiris theme has to happen here. Under any
# other theme this restores Omarchy's stock mark -- the same file, and the same
# effect, as `omarchy branding about reset`.
#
# The art itself is generated by ~/.local/bin/osiris-eye-logo; this hook only
# copies, so switching themes never waits on a Python start-up.
#
# Written through a temp file and mv: omarchy-launch-about re-renders whenever
# about.txt's mtime changes, so the swap has to be atomic or it can be read
# half-written.

set -euo pipefail

THEME_NAME="${1:-}"
ABOUT="$HOME/.config/omarchy/branding/about.txt"
EYE="$HOME/.config/omarchy/branding/osiris-eye.txt"
STOCK="${OMARCHY_PATH:-/usr/share/omarchy}/icon.txt"

if [[ "$THEME_NAME" == "osiris" ]]; then
  SOURCE="$EYE"
else
  SOURCE="$STOCK"
fi

# Nothing to do if the wanted logo is missing or is already in place.
[[ -f "$SOURCE" ]] || exit 0
cmp -s "$SOURCE" "$ABOUT" && exit 0

TMP=$(mktemp "$(dirname "$ABOUT")/.about.XXXXXX")
trap 'rm -f "$TMP"' EXIT
cp "$SOURCE" "$TMP"
chmod 644 "$TMP"
mv "$TMP" "$ABOUT"
trap - EXIT
